Repository grafana/tanka, pull requests merged in 2019-10, with the labels that each got.

#90 chore(packaging): preserve full git tag for docker
  .drone/docker-manifest.tmpl
Labels: kind/bug

#81 fix(cli): panic on missing env
  cmd/tk/env.go
Labels: component/cli, kind/bug

#84 feat(tool/imports): import analysis using upstream jsonnet
  go.mod
  go.sum
  pkg/jsonnet/eval.go
  pkg/jsonnet/imports.go
  pkg/jsonnet/imports_test.go
  pkg/jsonnet/jsonnet.go
  pkg/jsonnet/testdata/README.md
  pkg/jsonnet/testdata/jsonnetfile.json
  pkg/jsonnet/testdata/main.jsonnet
  pkg/jsonnet/testdata/test.svg
  pkg/jsonnet/testdata/trees.jsonnet
  pkg/jsonnet/testdata/trees/apple.jsonnet
  pkg/jsonnet/testdata/trees/cherry.jsonnet
  pkg/jsonnet/testdata/trees/generic.libsonnet
  pkg/jsonnet/testdata/trees/peach.jsonnet
  pkg/jsonnet/transitive.go
  pkg/native/funcs.go
Labels: component/tooling, kind/enhancement

#93 refactor: move pkg/jpath and pkg/native into pkg/jsonnet
  cmd/tk/jsonnet.go
  cmd/tk/other.go
  cmd/tk/tool.go
  docs/jsonnet/native.md
  pkg/jsonnet/eval.go
  pkg/jsonnet/imports.go
  pkg/jsonnet/jpath/jpath.go
  pkg/jsonnet/native/funcs.go
Labels: kind/enhancement

#92 refactor(cli): spec parsing
  cmd/tk/env.go
  cmd/tk/init.go
  cmd/tk/main.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_test.go
  pkg/spec/depreciations.go
  pkg/spec/depreciations_test.go
  pkg/spec/spec.go
  pkg/spec/v1alpha1/config.go
Labels: kind/enhancement

#97 refactor: api
  cmd/tk/env.go
  cmd/tk/init.go
  cmd/tk/jsonnet.go
  cmd/tk/main.go
  cmd/tk/util.go
  cmd/tk/workflow.go
  go.mod
  go.sum
  pkg/cli/alert.go
  pkg/cli/cmp/complete.go
  pkg/jsonnet/imports.go
  pkg/kubernetes/errors.go
  pkg/kubernetes/kubectl.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/kubernetes_test.go
  pkg/kubernetes/subsetdiff.go
  pkg/tanka/parse.go
  pkg/tanka/tanka.go
  pkg/tanka/workflow.go
  pkg/util/mapstr.go
Labels: kind/enhancement

#104 chore(bot): stale keepalive
  .github/stale.yml
Labels: kind/enhancement
