Repository grafana/tanka, pull requests merged in 2020-03, with the labels that each got.

#229 fix(docs): -t deployment example
  docs/docs/targets.md
Labels: component/docs, kind/bug

#231 fix(kubernetes): ignore diff errs on apply
  pkg/tanka/workflow.go
Labels: component/kubernetes, kind/bug

#228 feat: safer context parsing, general refactoring
  cmd/tk/export.go
  cmd/tk/init.go
  cmd/tk/status.go
  cmd/tk/util.go
  pkg/cli/cmp/complete.go
  pkg/jsonnet/eval.go
  pkg/jsonnet/native/funcs.go
  pkg/kubernetes/apply.go
  pkg/kubernetes/client/apply.go
  pkg/kubernetes/client/client.go
  pkg/kubernetes/client/context.go
  pkg/kubernetes/client/diff.go
  pkg/kubernetes/client/diff_test.go
  pkg/kubernetes/client/errors.go
  pkg/kubernetes/client/exec.go
  pkg/kubernetes/client/exec_test.go
  pkg/kubernetes/client/info.go
  pkg/kubernetes/client/kubectl.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/util/diff.go
  pkg/kubernetes/util/targetexp.go
  pkg/spec/errors.go
  pkg/spec/spec.go
  pkg/tanka/workflow.go
Labels: kind/enhancement

#239 fix(kubernetes): fmt related stack overflow
  pkg/kubernetes/client/errors.go
  pkg/kubernetes/kubernetes.go
Labels: component/kubernetes, kind/bug, priority/high

#237 fix(kubernetes): properly handle diff namespaces
  docs/docs/env-vars.md
  pkg/kubernetes/client/client.go
  pkg/kubernetes/client/diff.go
  pkg/kubernetes/client/diff_test.go
  pkg/kubernetes/client/exec.go
  pkg/kubernetes/client/resources.go
  pkg/kubernetes/client/resources_test.go
  pkg/kubernetes/diff.go
  pkg/kubernetes/diff_test.go
  pkg/kubernetes/kubernetes.go
Labels: component/kubernetes, kind/bug

#235 feat: standalone cli
  cmd/tk/args.go
  cmd/tk/env.go
  cmd/tk/export.go
  cmd/tk/init.go
  cmd/tk/jsonnet.go
  cmd/tk/main.go
  cmd/tk/status.go
  cmd/tk/tool.go
  cmd/tk/workflow.go
  docs/docs/completion.md
  go.mod
  go.sum
  pkg/cli/cmp/complete.go
  pkg/kubernetes/apply.go
  pkg/tanka/workflow.go
  pkg/term/alert.go
  pkg/term/colordiff.go
  pkg/term/colordiff_test.go
Labels: component/cli, kind/enhancement

#240 chore: bump go-jsonnet to 0.15
  go.mod
  go.sum
Labels: kind/enhancement

#242 Fixes for compatibility with windows style path environment variable.
  pkg/kubernetes/client/exec.go
  pkg/kubernetes/client/kubectl.go
Labels: kind/bug

#243 feat: more complete Dockerfile
  Dockerfile
Labels: kind/enhancement

#241 feat: Formatter
  cmd/tk/fmt.go
  cmd/tk/init.go
  cmd/tk/main.go
  go.mod
  go.sum
  pkg/kubernetes/diff.go
  pkg/kubernetes/diff_test.go
  pkg/tanka/format.go
Labels: kind/feature
