Repository grafana/tanka, pull requests merged in 2020-08, with the labels that each got.

#339 feat(cli): support negative filters
  docs/docs/targets.md
  pkg/process/filter.go
  pkg/process/process_test.go
Labels: component/cli, kind/feature

#340 feat(jsonnet): top level arguments
  cmd/tk/export.go
  cmd/tk/jsonnet.go
  cmd/tk/workflow.go
  docs/docs/jsonnet/injecting-values.md
  pkg/jsonnet/eval.go
  pkg/tanka/tanka.go
Labels: component/jsonnet, kind/feature

#338 fix(k8s): consistent types in manifest.Manifest
  pkg/kubernetes/manifest/manifest.go
  pkg/kubernetes/subsetdiff.go
Labels: component/kubernetes, kind/bug

#336 feat: provide std.native('helmTemplate')
  .gitignore
  docs/docs/env-vars.md
  pkg/helmraiser/helm.go
  pkg/helmraiser/helm_test.go
  pkg/jsonnet/native/funcs.go
Labels: component/jsonnet, component/kubernetes, kind/feature

#349 chore(release): Changelog for 0.12-alpha1
  CHANGELOG.md
Labels: component/docs

#357 feat(cli): fallback to PredictDirs
  cmd/tk/args.go
Labels: component/cli, kind/enhancement

#358 fix(manifest): yaml unmarshalling
  go.mod
  go.sum
  pkg/kubernetes/manifest/manifest.go
  pkg/kubernetes/manifest/manifest_test.go
Labels: kind/bug
