Repository grafana/tanka, pull requests merged in 2021-01, with the labels that each got.

#459 refactor(api): Loader interface
  cmd/tk/env.go
  cmd/tk/export.go
  pkg/jsonnet/eval.go
  pkg/jsonnet/jpath/dirs.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/spec/spec.go
  pkg/tanka/environments.go
  pkg/tanka/evaluators.go
  pkg/tanka/export.go
  pkg/tanka/inline.go
  pkg/tanka/load.go
  pkg/tanka/load_test.go
  pkg/tanka/parse.go
  pkg/tanka/prune.go
  pkg/tanka/static.go
  pkg/tanka/status.go
  pkg/tanka/tanka.go
  pkg/tanka/testdata/cases/withenv/main.jsonnet
  pkg/tanka/testdata/cases/withspecjson/main.jsonnet
  pkg/tanka/workflow.go
Labels: kind/enhancement

#412 feat(cli): run commands with tk- prefix on PATH
  cmd/tk/main.go
  cmd/tk/prefix.go
Labels: keepalive

#467 feat(api): Peek
  cmd/tk/env.go
  cmd/tk/export.go
  pkg/tanka/inline.go
  pkg/tanka/load.go
  pkg/tanka/static.go
Labels: component/api, kind/feature

#468 feat(api): Environment discovery
  cmd/tk/args.go
  cmd/tk/env.go
  cmd/tk/export.go
  pkg/tanka/environments.go
  pkg/tanka/list.go
Labels: component/api, kind/enhancement

#482 fix(jsonnet): Restore tk.env
  pkg/jsonnet/eval.go
  pkg/tanka/inline.go
  pkg/tanka/load.go
  pkg/tanka/parallel.go
  pkg/tanka/static.go
Labels: component/jsonnet, kind/bug
